# sqlite => postgresqlに変更

default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  # 追加
  encoding: unicode
  username: TwitterOutputter
  password:
  host: localhost

development:
  <<: *default
  database:  TwitterOutputter_development

test:
  <<: *default
  database:  TwitterOutputter_test

production:
  <<: *default
  # TODO ここよくわからない 環境変数?
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %> # 追加
